(global-aggressive-indent-mode 0)
(add-to-list 'aggressive-indent-excluded-modes 'coffee-mode)
(add-to-list 'aggressive-indent-excluded-modes 'python-mode)
(add-to-list 'aggressive-indent-excluded-modes 'jade-mode)
(add-to-list 'aggressive-indent-excluded-modes 'web-mode)
