(setq auto-mode-alist (cons '("\\.html$" . web-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.styl$" . jade-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.scss$" . css-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.js$" . web-mode) auto-mode-alist))
(setq auto-mode-alist (cons '("\\.hx$" . haxe-mode) auto-mode-alist))
(add-hook 'python-mode-hook 'ws-butler-mode)
;; (add-hook 'coffee-mode-hook 'ws-butler-mode)
;; (add-hook 'js-mode-hook 'js2-minor-mode)
;; (add-hook 'js-mode-hook 'hs-minor-mode)
(add-hook 'web-mode-hook 'hs-minor-mode)
