;;;; loading packages duh!
(load "~/.emacs.d/my-packages.el")

;;;; loading dependency setup
;; utils
(load "~/.emacs.d/cfg-exec-path-from-shell.el")
(load "~/.emacs.d/cfg-switch-window.el")
(load "~/.emacs.d/cfg-smex.el")
(load "~/.emacs.d/cfg-projectile.el")
(load "~/.emacs.d/cfg-flx-ido.el")
(load "~/.emacs.d/cfg-ido-vertical.el")
(load "~/.emacs.d/cfg-auto-complete.el")
(load "~/.emacs.d/cfg-smart-mode-line.el")
(load "~/.emacs.d/cfg-nyan.el")
(load "~/.emacs.d/cfg-undo-tree.el")
(load "~/.emacs.d/cfg-helm.el")
(load "~/.emacs.d/cfg-helm-swoop.el")
(load "~/.emacs.d/cfg-helm-projectile.el")
(load "~/.emacs.d/cfg-aggressive-indent.el")
(load "~/.emacs.d/cfg-guide-key.el")
(load "~/.emacs.d/cfg-evil-nerd-commenter.el")
(load "~/.emacs.d/cfg-org-mode.el")
(load "~/.emacs.d/cfg-linum-relative.el")
(load "~/.emacs.d/cfg-web-mode.el")
(load "~/.emacs.d/cfg-emmet-mode.el")
;; (load "~/.emacs.d/cfg-highlight-chars.el")
(load "~/.emacs.d/cfg-whitespace-cleanup-mode.el")
(load "~/.emacs.d/cfg-smartparens.el")
(load "~/.emacs.d/cfg-expand-region.el")
;; language specific
(load "~/.emacs.d/cfg-jedi.el")
;; (load "~/.emacs.d/cfg-coffee.el")
(load "~/.emacs.d/cfg-javascript.el")
(load "~/.emacs.d/cfg-jsx.el")
(load "~/.emacs.d/cfg-css.el")
;;;;
